name: nf-core-tpp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openms=2.4.0
  - thermorawfileparser=1.2.3
# removed as too old
#  - tpp=5.0.0
  - comet-ms=2019014
  - r-base=3.6.1

