name: nf-core-moff-labelfree
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:

  - python=3.6
  - moff=2.0.3
  - pandas=0.24.2
  - brain-isotopic-distribution=1.5.3
  - thermorawfileparser=1.1.11
  - searchgui=3.3.10
  - peptide-shaker=1.16.36
  - unzip=6.0 
  - mono=5.14.0.177
  - libopenblas=0.3.3
  - bioconductor-msnbase=2.14.1
#  - r=3.6.0
  - r-msqrob=0.7.6
