name: nf-core-moff-labelfree
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:

  - python=3.6
#  - moff=2.0.3
  - flashlfq=1.1.1
  - pandas=0.24.2
#  - brain-isotopic-distribution=1.5.3
  - thermorawfileparser=1.2.3
  - searchgui=4.0.7
  - peptide-shaker=2.0.5
  - unzip=6.0 
  - mono=5.14.0.177
  - libopenblas=0.3.3
  - bioconductor-msnbase=2.16.0
  - r-msqrob=0.7.6
  

